server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  region: us-east-1
  s3:
    mock: false
    buckets:
      customer: bucket-fullstack-customer-test

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,metrics,threaddump,prometheus
    enabled-by-default: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
    metrics:
      export:
        prometheus:
          enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer?currentSchema=testing-db
    username: testingDev
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet
    banner-mode: log
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: testing-db

application:
  title: Api Backend
  version: v1.0.0

spring-boot:
  version: v1.0.0