server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  region: us-east-1
  s3:
    mock: false
    buckets:
      customer: bucket-fullstack-customer-test

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,metrics,threaddump,prometheus
    enabled-by-default: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
    metrics:
      export:
        prometheus:
          enabled: true

spring:

  datasource:
    url: jdbc:postgresql://localhost:5332/customercatalog
    username: userTestingDev
    password: password

  jpa:

    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_catalog: customercatalog
        default_schema: customerschema

    show-sql: true
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: customerschema

application:
  title: Api Backend
  version: v1.0.0

spring-boot:
  version: v1.0.0